# -*- coding: utf-8 -*-
"""neuro120decays

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q68JFQmf6UfKGSq205l_BuNOM73Ymu-G
"""

# -*- coding: utf-8 -*-
"""Adaptive TBRS model based on Python translation of the original C implementation."""

import math
import random
import sys
import time

# CONSTANTS
NB_UNIT_BLOCKS = 9
SIZE_OF_POSITION_BLOCKS = 6
MAX_POSITION = 16
MAX_MEMORANDA = 10
MAX_DISTRACTORS = 90
MAX_ITEM = MAX_MEMORANDA + MAX_DISTRACTORS
NB_ITEM_UNITS = 64
DISTRACTOR_ENCODING_WEIGHT = 0.5

# COLORS
RED   = "\x1B[1;31;47m"
BLU   = "\x1B[1;34;47m"
YEL   = "\x1B[1;30;43m"
CYN   = "\x1B[1;37;46m"
MAG   = "\x1B[35m"
WHT   = "\x1B[37m"
RESET = "\x1B[0m"

# BASE PARAMETERS
param_P = 0.3
param_R = 6.0
param_s = 1.0
param_tauE = 0.95
param_L = 1.0 / 9.0
param_theta = 0.05
param_sigma = 0.02
param_D = 0.5
param_Tr = 0.08
param_tauOp = 0.95
param_Ta = 0.5
param_freeTime = 1.0
param_freeTimeIncludesOpDuration = 1
param_refreshLastStopped = 0
param_attentionalFocusSize = 1
nbmemo = 7
param_memoDistr = 1.0
nbop = 4
presentationTime = 1.5
param_deterministic = 0
param_itemDistractorOverlap = 0.4
param_itemDistractorNoise = 1.0
param_itemItemOverlap = 0.4
param_sameDist = 0

# ADAPTIVE DECAY PARAMETERS
adaptive_mode = "fixed"          # options: fixed, linear, threshold, interference
adaptive_alpha = 0.25            # strength for linear/interference modes
adaptive_threshold = 0.35        # threshold for threshold mode
adaptive_high_decay = 0.7        # decay above threshold
adaptive_low_decay = 0.4         # decay below threshold

# MODEL VARIABLES
var_te = 0.0
var_tr = 0.0
var_eta = 0.0
var_r = 0.0
var_tauR = 0.0
var_Rop = 0.0
var_rop = 0.0
var_ta = 0.0

# IMPLEMENTATION VARIABLES
VERBOSE = 0
QUIET = 0
logTauE = 0.0
globalTime = 0.0
nbPositionUnits = NB_UNIT_BLOCKS * SIZE_OF_POSITION_BLOCKS
lastItem = 0
distractorNumber = 0

# Optional: store adaptive decay values for inspection/plotting later
decay_trace = []


def error(s1, s2=""):
    print(f"{s1} {s2}")
    sys.exit(1)


def pr2(x):
    if x == 1:
        print(" 1 ", end="")
    elif x == -1:
        print(" -1", end="")
    elif x == 0:
        print(" 0 ", end="")
    else:
        tmp = int(100 * x)
        if tmp < 0:
            tmp = -tmp
            print("-", end="")
        if tmp < 10:
            print(f".0{tmp}", end="")
        else:
            print(f".{tmp}", end="")


def name(code):
    if code <= MAX_MEMORANDA:
        if code < 26:
            return chr(code + ord('A') - 1)
        return '*'
    else:
        code_dist = code - MAX_MEMORANDA
        if code_dist < 10:
            return chr(code_dist + ord('1') - 1)
        return '#'


def random_normal(mean, std):
    # protect against log(0)
    u = max(random.random(), 1e-12)
    v = random.random()
    return mean + std * math.sqrt(-2 * math.log(u)) * math.cos(2 * math.pi * v)


def display_item_pos_associations(item_position_matrix, last_position):
    for i in range(1, last_position + 1):
        print(f"   {chr(i + ord('A') - 1)}: ", end="")
        for j in range(1, 3 * SIZE_OF_POSITION_BLOCKS + 1):
            print(f".{int(1000 * item_position_matrix[i][j]) % 1000}/", end="")
        print("...")
    return 0


def display_item_units(item_vectors_in_wm, item):
    print(f"   {name(item)}: ", end="")
    for i in range(1, min(64, NB_ITEM_UNITS)):
        pr2(item_vectors_in_wm[item][i])
    print()
    return 0


def create_random_pattern(pattern, min_idx, max_idx):
    for i in range(min_idx, max_idx + 1):
        pattern[i] = random.random()


def create_similar_random_pattern(pattern, ref_pattern, std, min_idx, max_idx):
    for i in range(min_idx, max_idx + 1):
        if ref_pattern[i] == -1:
            val = random.random()
        else:
            val = random_normal(ref_pattern[i], std)
            if val < 0:
                val = 0
            elif val > 1:
                val = 1
        pattern[i] = val


def create_overlapping_random_pattern(pattern, ref_pattern, pattern_size, p):
    global VERBOSE, param_itemDistractorNoise

    if VERBOSE:
        print(
            f"   Create a distractor sharing {int(p * 100)}% units with the item at previous position"
        )

    i = 1
    while i <= pattern_size and int(ref_pattern[i]) == -1:
        pattern[i] = -1
        i += 1

    first_used_unit = i

    num_neg = int((1 - p) * pattern_size / 4)
    for _ in range(num_neg):
        pattern[i] = -1
        i += 1

    create_similar_random_pattern(
        pattern,
        ref_pattern,
        param_itemDistractorNoise,
        i,
        i + pattern_size // 4
    )

    for c in range(first_used_unit + pattern_size // 4, first_used_unit, -1):
        alea = random.randrange(pattern_size // 4) + first_used_unit
        pattern[alea], pattern[c] = pattern[c], pattern[alea]

    for c in range(i + pattern_size // 4 + 1, pattern_size + 1):
        pattern[c] = -1


def rmse(v1, v2, size):
    total = 0.0
    for i in range(1, size + 1):
        diff = v1[i] - v2[i]
        total += diff * diff
    return math.sqrt(total / size)


def decay(item_position_matrix, factor, excluded_item):
    for i in range(1, MAX_ITEM + 1):
        if excluded_item == -1 or i != excluded_item:
            for j in range(1, nbPositionUnits + 1):
                if item_position_matrix[i][j] != 0:
                    item_position_matrix[i][j] *= factor


def interfere(old_item_vector, new_item_vector, p):
    for j in range(1, NB_ITEM_UNITS + 1):
        if (
            old_item_vector[j] != new_item_vector[j]
            and int(old_item_vector[j]) != -1
            and int(new_item_vector[j]) != -1
        ):
            old_item_vector[j] = old_item_vector[j] * (1 - p) + new_item_vector[j] * p


# -----------------------------
# ADAPTIVE DECAY HELPERS
# -----------------------------
def get_cognitive_load():
    if param_Ta + param_freeTime == 0:
        return 0.0
    load = param_Ta / (param_Ta + param_freeTime)
    return max(0.0, min(1.0, load))


def get_interference_history():
    raw = distractorNumber * param_itemDistractorOverlap / max(1, nbop * nbmemo)
    return max(0.0, min(1.0, raw))


def get_decay_rate():
    base = param_D

    if adaptive_mode == "fixed":
        return base

    elif adaptive_mode == "linear":
        load = get_cognitive_load()
        return base * (1.0 + adaptive_alpha * load)

    elif adaptive_mode == "threshold":
        load = get_cognitive_load()
        return adaptive_high_decay if load >= adaptive_threshold else adaptive_low_decay

    elif adaptive_mode == "interference":
        hist = get_interference_history()
        return base * (1.0 + adaptive_alpha * hist)

    elif adaptive_mode == "log":
        load = get_cognitive_load()
        return base * (1.0 + adaptive_alpha * math.log(1.0 + load))

    else:
        error("Unknown adaptive_mode:", adaptive_mode)


def apply_decay(item_position_matrix, duration, excluded_item):
    current_decay = get_decay_rate()
    decay_trace.append(current_decay)
    decay(item_position_matrix, math.exp(-current_decay * duration), excluded_item)


def retrieve(position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
             item_position_matrix, item_strength, pos, status):
    global var_tr, globalTime, VERBOSE

    if status == 0:
        var_r_local = random_normal(param_R, param_s)
        if var_r_local < 0.1:
            var_r_local = 0.1
        var_tr = logTauE / var_r_local
        if var_tr > presentationTime:
            var_tr = presentationTime

    retrieval_duration = var_tr
    activation_max = -99999.0
    best_wm_item = -1

    if VERBOSE:
        print(f"[{globalTime:.2f}s] ", end="")

    activation_values = [0.0] * (MAX_MEMORANDA + distractorNumber + 1)

    for item in range(1, MAX_MEMORANDA + distractorNumber + 1):
        total = 0.0

        for i in range(1, nbPositionUnits + 1):
            if position_vectors[pos][i] != 0:
                total += position_vectors[pos][i] * item_position_matrix[item][i]

        total += random_normal(0, 1) * max(param_sigma, 0.0001)

        if VERBOSE:
            activation_values[item] = total

        if total > activation_max:
            activation_max = total
            best_wm_item = item

    if VERBOSE:
        switch_to_distractors = False
        for item in range(1, MAX_MEMORANDA + distractorNumber + 1):
            if item > MAX_MEMORANDA and not switch_to_distractors:
                print("... ", end="")
                switch_to_distractors = True

            if item == best_wm_item:
                print(RED, end="")

            if item <= 26 and item <= MAX_MEMORANDA:
                print(f"{chr(item + ord('A') - 1)}:", end="")
                pr2(activation_values[item])
            elif item > MAX_MEMORANDA:
                print(f"{item - MAX_MEMORANDA}:", end="")
                pr2(activation_values[item])

            if item == best_wm_item:
                print(RESET, end="")
            print(" ", end="")
        print()

    if activation_max < param_theta:
        if VERBOSE:
            print("No memoranda are above the theta threshold.")
        return 0, activation_max, retrieval_duration, best_wm_item
    else:
        min_rmse = 99999.0
        retrieved_item = 0
        for item in range(1, MAX_MEMORANDA + distractorNumber + 1):
            a_rmse = rmse(item_vectors_in_wm[best_wm_item], item_vectors_in_ltm[item], NB_ITEM_UNITS)
            if a_rmse < min_rmse:
                min_rmse = a_rmse
                retrieved_item = item

        if VERBOSE:
            print(
                f"   {CYN}Pos{pos}: {name(retrieved_item)} ({activation_max:.2f}) is the closest LTM item "
                f"to the best WM item ({name(best_wm_item)}) (RMSE={min_rmse:.4f}){RESET}"
            )

        return retrieved_item, activation_max, retrieval_duration, best_wm_item


def encode(position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
           item_position_matrix, item_strength, initial_encoding,
           current_item, best_wm_item, position, time_left,
           strength_divisor, duration, distractor):
    global var_te, var_eta, var_tr, globalTime, distractorNumber

    if distractor:
        current_item_symbol = chr(current_item - MAX_MEMORANDA + ord('0'))
    else:
        current_item_symbol = chr(current_item + ord('A') - 1)

    var_r_local = random_normal(param_R, param_s)
    if var_r_local < 0.1:
        var_r_local = 0.1

    if initial_encoding:
        if distractor:
            encoding_duration = 0.0
        else:
            for j in range(1, NB_ITEM_UNITS + 1):
                item_vectors_in_wm[current_item][j] = item_vectors_in_ltm[current_item][j]

            var_te = logTauE / var_r_local
            if var_te > presentationTime:
                var_te = presentationTime
            encoding_duration = var_te

            if VERBOSE:
                print(f"[{globalTime:.2f}s]   ({distractor}) Encoding duration of {current_item_symbol} = {encoding_duration:1.3f}")

            var_eta = 1 - math.exp(-var_r_local * encoding_duration)
    else:
        if duration == -1:
            var_tr = -math.log(1 - var_tauR) / var_r_local
            if var_tr > time_left:
                var_tr = time_left
            encoding_duration = var_tr
        else:
            encoding_duration = duration

        var_eta = 1 - math.exp(-var_r_local * encoding_duration)
        var_eta /= strength_divisor

    globalTime += encoding_duration

    if (not distractor) and duration == -1:
        apply_decay(item_position_matrix, encoding_duration, current_item)

    if distractor:
        retrieved_item, activation_max, retrieval_duration, _tmp = retrieve(
            position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
            item_position_matrix, item_strength, position, 1
        )

        if param_sameDist == 1:
            if distractorNumber == 0:
                distractorNumber = 1
                create_overlapping_random_pattern(
                    item_vectors_in_ltm[MAX_MEMORANDA + distractorNumber],
                    item_vectors_in_wm[retrieved_item],
                    NB_ITEM_UNITS,
                    param_itemDistractorOverlap,
                )
        else:
            create_overlapping_random_pattern(
                item_vectors_in_ltm[MAX_MEMORANDA + distractorNumber],
                item_vectors_in_wm[retrieved_item],
                NB_ITEM_UNITS,
                param_itemDistractorOverlap,
            )

        for j in range(1, NB_ITEM_UNITS + 1):
            item_vectors_in_wm[MAX_MEMORANDA + distractorNumber][j] = item_vectors_in_ltm[MAX_MEMORANDA + distractorNumber][j]

        if VERBOSE:
            display_item_units(item_vectors_in_wm, MAX_MEMORANDA + distractorNumber)
            display_item_units(item_vectors_in_wm, lastItem)

        interfere(
            item_vectors_in_wm[retrieved_item],
            item_vectors_in_wm[MAX_MEMORANDA + distractorNumber],
            DISTRACTOR_ENCODING_WEIGHT
        )

        if VERBOSE:
            print(f"   {YEL}{name(retrieved_item)} is retrieved at position {position} and altered by the distractor{RESET}")
            display_item_units(item_vectors_in_wm, retrieved_item)

        var_eta *= DISTRACTOR_ENCODING_WEIGHT

    for j in range(1, nbPositionUnits + 1):
        if position_vectors[position][j] != 0:
            item_position_matrix[current_item][j] += (param_L - item_position_matrix[current_item][j]) * var_eta

    if (not initial_encoding) and (not distractor):
        if VERBOSE:
            print(f"   Move WM item {name(best_wm_item)} closer to LTM item {name(current_item)}")
        interfere(item_vectors_in_wm[best_wm_item], item_vectors_in_ltm[current_item], 0.5)
        if VERBOSE:
            display_item_units(item_vectors_in_wm, best_wm_item)

    return encoding_duration


def refresh(position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
            item_position_matrix, item_strength, time_available, last_position):
    current_position = 1
    while time_available > 0:
        afsi = min(param_attentionalFocusSize, last_position)
        cpi = current_position
        reencoding_duration = -1

        while afsi > 0:
            best_ltm_item, activation_max, retrieval_duration, best_wm_item = retrieve(
                position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                item_position_matrix, item_strength, cpi, 1
            )

            if VERBOSE:
                print(f"   {CYN}It is refreshed.{RESET}")

            reencoding_duration = encode(
                position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                item_position_matrix, item_strength,
                0, best_ltm_item, best_wm_item, cpi,
                time_available,
                min(param_attentionalFocusSize, last_position),
                reencoding_duration,
                0
            )

            if VERBOSE:
                print(f"   {name(best_ltm_item)} is reencoded in {reencoding_duration:1.3f} ms")

            cpi += 1
            if cpi > last_position:
                cpi = 1
            afsi -= 1

        current_position = cpi
        time_available -= reencoding_duration
        if time_available < 0:
            time_available = 0

    return 0


def processing(position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
               item_position_matrix, item_strength, last_position):
    global var_Rop, var_rop, var_ta, globalTime

    var_Rop = -math.log(1 - param_tauOp) / param_Ta
    var_rop = random_normal(var_Rop, param_s)
    if var_rop < 0.1:
        var_rop = 0.1
    var_ta = -math.log(1 - param_tauOp) / var_rop

    if (var_ta > param_freeTime) and (param_freeTimeIncludesOpDuration == 1):
        if VERBOSE:
            print(f"   Process stopped. Planned to last {var_ta:1.3f} ms but no free time left.")
        var_ta = param_freeTime

    if VERBOSE:
        print(f"[{globalTime:.2f}s]   Processing duration={var_ta:1.3f}")

    encode(
        position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
        item_position_matrix, item_strength,
        1, MAX_MEMORANDA + distractorNumber, -1,
        last_position, 9999, 1, var_ta, 1
    )

    globalTime += var_ta
    apply_decay(item_position_matrix, var_ta, -1)
    return var_ta


def recall(position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
           item_position_matrix, item_strength, last_position):
    global globalTime
    recalled = []

    for position in range(1, last_position + 1):
        best_ltm_item, activation_max, retrieval_duration, best_wm_item = retrieve(
            position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
            item_position_matrix, item_strength, position, 0
        )

        if retrieval_duration > 5:
            retrieval_duration = 5

        apply_decay(item_position_matrix, retrieval_duration, -1)

        if activation_max > param_theta:
            if 1 <= best_ltm_item <= 26:
                code_item = chr(best_ltm_item + ord('A') - 1)
            else:
                code_item = '*'

            for j in range(1, nbPositionUnits + 1):
                if item_vectors_in_wm[best_ltm_item][j] != 0:
                    item_position_matrix[best_ltm_item][j] -= param_L * activation_max
        else:
            code_item = '.'

        if VERBOSE:
            print(f"   {RED}position {position}: {code_item} is retrieved{RESET}")

        recalled.append(code_item)
        globalTime += retrieval_duration

    return "".join(recalled)


def compare_stim_and_recalled(recalled, last_position, res_serial_position_data):
    total_order = 0
    for i in range(last_position):
        if recalled[i] == chr(ord('A') + i):
            total_order += 1
            res_serial_position_data[i + 1] += 1
    return total_order / last_position


def generate_position_representations(position_vectors):
    for i in range(1, nbPositionUnits + 1):
        position_vectors[1][i] = 0

    for i in range(0, NB_UNIT_BLOCKS):
        random_position = 1 + random.randrange(SIZE_OF_POSITION_BLOCKS)
        position_vectors[1][i * SIZE_OF_POSITION_BLOCKS + random_position] = 1

    for p in range(2, MAX_POSITION + 1):
        for i in range(0, NB_UNIT_BLOCKS):
            if random.randrange(100) > param_P * 100:
                for j in range(i * SIZE_OF_POSITION_BLOCKS + 1, (i + 1) * SIZE_OF_POSITION_BLOCKS + 1):
                    position_vectors[p][j] = 0
                random_position = 1 + random.randrange(SIZE_OF_POSITION_BLOCKS)
                position_vectors[p][i * SIZE_OF_POSITION_BLOCKS + random_position] = 1
            else:
                for j in range(i * SIZE_OF_POSITION_BLOCKS + 1, (i + 1) * SIZE_OF_POSITION_BLOCKS + 1):
                    position_vectors[p][j] = position_vectors[p - 1][j]

    if VERBOSE:
        print("POSITION UNITS")
        for p in range(1, MAX_POSITION + 1):
            print(f"   [{p:2d}] ", end="")
            for i in range(1, nbPositionUnits + 1):
                print(position_vectors[p][i], end="")
            print()


def generate_item_representations(item_vectors, d1, d2):
    for i in range(1, MAX_MEMORANDA + 1):
        for j in range(1, NB_ITEM_UNITS + 1):
            item_vectors[i][j] = -1
        create_random_pattern(item_vectors[i], 1, NB_ITEM_UNITS // 4)

    for i in range(MAX_MEMORANDA + 1, MAX_ITEM + 1):
        for j in range(1, NB_ITEM_UNITS + 1):
            item_vectors[i][j] = -1

    if VERBOSE:
        print("ITEM UNITS (first 64 units)")
        for p in range(1, min(26, MAX_MEMORANDA) + 1):
            display_item_units(item_vectors, p)


def parse_args(argv):
    global VERBOSE, QUIET, nbmemo, param_memoDistr, nbop
    global param_R, param_P, param_s, param_D, param_theta, param_sigma
    global param_Tr, param_Ta, param_freeTime, param_freeTimeIncludesOpDuration
    global param_deterministic, param_sameDist, param_itemDistractorNoise
    global param_itemItemOverlap, param_itemDistractorOverlap
    global adaptive_mode, adaptive_alpha, adaptive_threshold
    global adaptive_high_decay, adaptive_low_decay

    nb_simulations = 1

    syntax = """Syntax:
  ?                         this message
  -v                        verbose
  -q                        quiet
  -n <value>                number of simulations
  nbmemo <value>            number of items
  memoDistr <value>         percentage of memo in domain 1
  nbop <value>              number of operations
  R <value>                 mean memory processing rate
  P <value>                 proportion of units maintained
  s <value>                 std of processing rates
  theta <value>             retrieval threshold
  sigma <value>             retrieval noise
  D <value>                 base decay rate
  Tr <value>                refresh time
  Ta <value>                attentional capture duration
  freeTime <value>          free time after processing
  ftiod <0|1>               free time includes operation duration
  determ <0|1>              deterministic behavior
  sameDist <0|1>            identical distractors or not
  idn <value>               distractor noise
  iio <value>               item-item overlap
  ido <value>               item-distractor overlap

  decayMode <fixed|linear|threshold|interference>
  alpha <value>             adaptive strength
  decayThreshold <value>    threshold for threshold mode
  highDecay <value>         high decay value
  lowDecay <value>          low decay value
"""

    i = 1
    while i < len(argv):
        arg = argv[i]
        if arg == "?":
            error(syntax, "")
        elif arg == "-v":
            VERBOSE = 1
            i += 1
        elif arg == "-q":
            QUIET = 1
            i += 1
        elif arg == "-n":
            nb_simulations = int(argv[i + 1]); i += 2
        elif arg == "nbmemo":
            nbmemo = int(argv[i + 1]); i += 2
        elif arg == "memoDistr":
            param_memoDistr = float(argv[i + 1]); i += 2
        elif arg == "nbop":
            nbop = int(argv[i + 1]); i += 2
        elif arg == "R":
            param_R = float(argv[i + 1]); i += 2
        elif arg == "P":
            param_P = float(argv[i + 1]); i += 2
        elif arg == "s":
            param_s = float(argv[i + 1]); i += 2
        elif arg == "D":
            param_D = float(argv[i + 1]); i += 2
        elif arg == "theta":
            param_theta = float(argv[i + 1]); i += 2
        elif arg == "sigma":
            param_sigma = float(argv[i + 1]); i += 2
        elif arg == "Tr":
            param_Tr = float(argv[i + 1]); i += 2
        elif arg == "Ta":
            param_Ta = float(argv[i + 1]); i += 2
        elif arg == "freeTime":
            param_freeTime = float(argv[i + 1]); i += 2
        elif arg == "ftiod":
            param_freeTimeIncludesOpDuration = int(argv[i + 1]); i += 2
        elif arg == "determ":
            param_deterministic = int(argv[i + 1]); i += 2
        elif arg == "sameDist":
            param_sameDist = int(argv[i + 1]); i += 2
        elif arg == "idn":
            param_itemDistractorNoise = float(argv[i + 1]); i += 2
        elif arg == "iio":
            param_itemItemOverlap = float(argv[i + 1]); i += 2
        elif arg == "ido":
            param_itemDistractorOverlap = float(argv[i + 1]); i += 2
        elif arg == "decayMode":
            adaptive_mode = argv[i + 1].strip().lower(); i += 2
        elif arg == "alpha":
            adaptive_alpha = float(argv[i + 1]); i += 2
        elif arg == "decayThreshold":
            adaptive_threshold = float(argv[i + 1]); i += 2
        elif arg == "highDecay":
            adaptive_high_decay = float(argv[i + 1]); i += 2
        elif arg == "lowDecay":
            adaptive_low_decay = float(argv[i + 1]); i += 2
        else:
            error("Unknown parameter:", arg)

    if nbop > 16:
        error("Cannot handle more than 16 operations.", "")

    if param_itemDistractorOverlap < 0 or param_itemDistractorOverlap > 1:
        error("Item distractor overlap should be between 0 and 1.", "")

    return nb_simulations


def main(argv=None):
    global logTauE, var_tauR, distractorNumber, globalTime, lastItem, decay_trace

    if argv is None:
        argv = sys.argv

    nb_simulations = parse_args(argv)

    if param_deterministic:
        random.seed(param_deterministic)
    else:
        random.seed(int(time.time()))

    item_position_matrix = [[0.0] * (nbPositionUnits + 1) for _ in range(MAX_ITEM + 1)]
    item_strength = [0.0] * (MAX_ITEM + 1)
    position_vectors = [[0] * (nbPositionUnits + 1) for _ in range(MAX_POSITION + 1)]
    item_vectors_in_wm = [[0.0] * (NB_ITEM_UNITS + 1) for _ in range(MAX_ITEM + 1)]
    item_vectors_in_ltm = [[0.0] * (NB_ITEM_UNITS + 1) for _ in range(MAX_ITEM + 1)]

    stimuli = []
    for i in range(nbmemo):
        stimuli.append(chr(65 + i))
        for j in range(1, nbop + 1):
            stimuli.append(chr(j + ord('0')))
    stimuli.append('#')

    res_serial_position_data = [0.0] * (MAX_POSITION + 1)
    res_prop_correct = 0.0

    logTauE = -math.log(1 - param_tauE)
    var_tauR = 1 - math.exp(-param_R * param_Tr)

    decay_trace = []

    for cpt_replic in range(1, nb_simulations + 1):
        globalTime = 0.0

        generate_position_representations(position_vectors)
        generate_item_representations(item_vectors_in_ltm, 1, 0)

        for i in range(1, MAX_ITEM + 1):
            for j in range(1, nbPositionUnits + 1):
                item_position_matrix[i][j] = 0.0

        for i in range(1, MAX_ITEM + 1):
            item_strength[i] = 0.0

        last_position = 0
        distractorNumber = 0

        idxstimulus = 0
        while True:
            symbol = stimuli[idxstimulus]
            idxstimulus += 1

            if 'A' <= symbol <= 'Z':
                if VERBOSE:
                    print(f"{RED}\n   MEMORIZING {symbol}   \n{RESET}")

                last_position += 1
                lastItem = ord(symbol) - ord('A') + 1

                encoding_duration = encode(
                    position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                    item_position_matrix, item_strength,
                    1, lastItem, -1, last_position,
                    presentationTime, 1, -1, 0
                )

                if VERBOSE:
                    display_item_pos_associations(item_position_matrix, last_position)

                if encoding_duration < 0:
                    error("There should be no error in initial encoding...", "")

                refresh(
                    position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                    item_position_matrix, item_strength,
                    presentationTime - encoding_duration, last_position
                )

                if VERBOSE:
                    display_item_pos_associations(item_position_matrix, last_position)

            elif '0' <= symbol <= chr(ord('9') + 7):
                if VERBOSE:
                    print(f"{RED}\n   PROCESSING {symbol}   \n{RESET}")

                if distractorNumber > MAX_DISTRACTORS:
                    error("number of distractors is higher than what is allowed in the program. Increase MAX_DISTRACTORS", "")

                if param_sameDist == 0:
                    distractorNumber += 1

                processing_duration = processing(
                    position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                    item_position_matrix, item_strength, last_position
                )

                if param_freeTimeIncludesOpDuration:
                    time_left = param_freeTime - processing_duration
                else:
                    time_left = param_freeTime

                if VERBOSE:
                    display_item_pos_associations(item_position_matrix, last_position)

                refresh(
                    position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                    item_position_matrix, item_strength,
                    time_left, last_position
                )

                if VERBOSE:
                    display_item_pos_associations(item_position_matrix, last_position)

            elif symbol == '#':
                if VERBOSE:
                    print(f"{RED}\n   RECALL   \n{RESET}")

                recalled = recall(
                    position_vectors, item_vectors_in_wm, item_vectors_in_ltm,
                    item_position_matrix, item_strength, last_position
                )

                if not QUIET:
                    print(f"#{cpt_replic:4d}: Recalled = {recalled}", file=sys.stderr)

                res_prop_correct += compare_stim_and_recalled(
                    recalled, last_position, res_serial_position_data
                )
                break

            else:
                error("Unknown symbol in stimulus", "")

    print("NBSimulations NbMemo NbOp ProportionCorrect P R s tauE L theta sigma D Tr tauOp Ta freeTime ftIncludesOp refreshLastStopped attentionalFocusSize decayMode ", end="")
    for i in range(1, nbmemo + 1):
        print(f"Pos{i} ", end="")
    print()

    print(
        f"{nb_simulations} {nbmemo} {nbop} {res_prop_correct / nb_simulations:1.3f} "
        f"{param_P:1.3f} {param_R:1.3f} {param_s:1.3f} {param_tauE:1.3f} {param_L:1.3f} "
        f"{param_theta:1.3f} {param_sigma:1.3f} {param_D:1.3f} {param_Tr:1.3f} "
        f"{param_tauOp:1.3f} {param_Ta:1.3f} {param_freeTime:1.3f} "
        f"{param_freeTimeIncludesOpDuration} {param_refreshLastStopped} {param_attentionalFocusSize} {adaptive_mode} ",
        end=""
    )

    for i in range(1, nbmemo + 1):
        print(f"{res_serial_position_data[i] / nb_simulations:1.4f} ", end="")
    print()


if __name__ == "__main__":
    main()